---
# tasks file for pan-azure-deploy
- name: Remove Subnet8
  azure_rm_subnet:
      client_id: "{{ client_id }}"
      tenant: "{{ tenant }}"
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      name: "{{ tenant_subnet8 }}"
      virtual_network_name: "{{ tenant_vnet }}"
      resource_group: "{{ tenant_rg }}"
      state: absent

- name: Create subnets 
  azure_rm_subnet:
      client_id: "{{ client_id }}"
      tenant: "{{ tenant }}"
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      name: "{{ item.name }}"
      virtual_network_name: "{{ tenant_vnet }}"
      resource_group: "{{ tenant_rg }}"
      address_prefix_cidr: "{{ item.prefix }}"
  with_items: "{{ subnets }}"

- name: Create Resource Group
  azure_rm_resourcegroup:
      client_id: "{{ client_id }}"
      tenant: "{{ tenant }}"
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      name: "{{ vfw_rg }}"
      location: "{{ location }}"

- name: Create Storage Account
  azure_rm_storageaccount:
      client_id: "{{ client_id }}"
      tenant: "{{ tenant }}"
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      resource_group: "{{ vfw_rg }}"
      name: "{{ vfw_sa }}"
      type: "{{ storage_sku }}"

- name: Deploy Firewall from Template
  azure_rm_deployment:
      client_id: "{{ client_id }}"
      tenant: "{{ tenant }}"
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      state: present
      resource_group_name: "{{ vfw_rg }}"
      location: "{{ location }}"
      template_link: 'https://raw.githubusercontent.com/pmusolino-rms/rms-pan-azure-hplus-tenant/master/AzureDeploy.json'
      parameters:
          vmName:
              value: "{{ vpan_name }}"
          storageAccountName:
              value: "{{ vfw_sa }}"
          storageAccountExistingRG:
              value:  "{{ vfw_rg }}"
          vmSize:
              value: "{{ vfw_size }}"
          imageVersion:
              value: "{{ vfw_version }}"
          imageSku:
              value: "{{ vfw_sku }}"
          virtualNetworkName:
              value: "{{ tenant_vnet }}"
          virtualNetworkAddressPrefix:
              value: "{{ tenant_prefix }}"
          virtualNetworkExistingRGName:
              value: "{{ tenant_rg }}"
          subnet0Name:
              value: "{{ tenant_vfw_mgmt }}"
          subnet1Name:
              value: "{{ tenant_vfw_untrust }}"
          subnet2Name:
              value: "{{ tenant_vfw_trust }}"
          subnet0Prefix:
              value: "{{ tenant_vfw_mgmt_prefix }}"
          subnet1Prefix:
              value: "{{ tenant_vfw_untrust_prefix }}"
          subnet2Prefix:
              value: "{{ tenant_vfw_trust_prefix }}"
          subnet0StartAddress:
              value: "{{ vfw_mgmt_ip }}"
          subnet1StartAddress:
              value: "{{ vfw_untrust_ip }}"
          subnet2StartAddress:
              value: "{{ vfw_trust_ip }}"
          adminUsername:
              value: "{{ vpan_admin }}"
          adminPassword:
              value: "{{ vpan_password }}"
          publicIPAddressName:
              value: "{{ vpan_name }}"
  tags: deploy

- name: Create Public IP address
  azure_rm_publicipaddress:
      client_id: "{{ client_id }}"
      tenant: "{{ tenant }}"
      subscription_id: "{{ subscription_id }}"
      secret: "{{ secret }}"
      resource_group: "{{ vfw_rg }}"
      name: "{{ vfw_untrust_ip_dns }}"
      allocation_method: Static
      location: "{{ location }}"
      domain_name: "{{ vfw_untrust_ip_dns }}"
  tags: pubip
## Unable to do the below: https://github.com/ansible/ansible/issues/29607
#- name: Associate IP with Nic
#  azure_rm_networkinterface:
#      name: "{{ vfw_untrust_nic }}"
#      resource_group: "{{ vfw_rg }}"
#      virtual_network_name: "{{ tenant_vnet }}"
#      public_ip_address_name: "{{ vfw_untrust_ip_dns }}"
#      subnet_name: "{{ tenant_vfw_untrust }}"
#  tags: pubip