---
# tasks file for pan-azure-security
- name: Create Security rules
  azure_rm_securitygroup:
      resource_group: "{{ vfw_rg }}"
      name: "{{ vfw_nsg }}"
      purge_rules: yes
      rules:
          - name: "Allow Location"
            protocol: TCP
            destination_port: 22,443
            access: Allow
            priority: 100
            direction: Inbound
            source_address_prefix: "{{ subnet1 }}"
          - name: "Allow Newark"
            protocol: TCP
            destination_port: 22,443
            access: Allow
            priority: 100
            direction: Inbound
            source_address_prefix: "{{ subnet2 }}"
          - name: "Allow Newark"
            protocol: TCP
            destination_port: 22,443
            access: Allow
            priority: 100
            direction: Inbound
            source_address_prefix: "{{ subnet3 }}"
          - name: "Allow Newark"
            protocol: TCP
            destination_port: 22,443
            access: Allow
            priority: 100
            direction: Inbound
            source_address_prefix: "{{ subnet4 }}"
          - name: "Allow Newark"
            protocol: TCP
            destination_port: 22,443
            access: Allow
            priority: 100
            direction: Inbound
            source_address_prefix: "{{ ansible-host }}"
