---
# tasks file for pan-azure-security
- name: Generate Management Profile rules
  template: src=pan_sec.j2 dest=/tmp/{{vpan_name}}_sec.txt

- name: Install MGMT Security profile from template
  napalm_install_config:
      provider: "{{ provider }}"
      config_file: /tmp/{{ vpan_name }}_sec.txt
      get_diffs: False
      commit_changes: True

- name: Generic management settings
  panos_mgtconfig:
      ip_address: '{{ vfw_fqdn }}'
      username: '{{ vpan_admin }}'
      password: '{{ vpan_password }}'
      timezone: '{{ tz  }}'
      login_banner: '{{ banner }}'
      commit: true